# import gymnasium as gym
# from gymnasium import spaces
# import numpy as np
# import os
# import cv2

# # def _load_dataset(self, path):
# #     # Path to the split file generated by your Data Pipeline
# #     split_file = os.path.join(path, "../../splits/train.txt")
# #     if os.path.exists(split_file):
# #         with open(split_file, 'r') as f:
# #             return f.readlines()
# #     return [] # Ensure you have run the Data Pipeline first!

# class AdaptiveInferenceEnv(gym.Env):
#     """
#     Custom Environment for RL-powered YOLO model selection.
#     State: Cheap visual features + temporal metadata.
#     Action: 0 (Nano), 1 (Small), 2 (Large).
#     """
#     def __init__(self, dataset_path, window_size=10, latency_weight=0.5):
#         super(AdaptiveInferenceEnv, self).__init__()
        
#         self.window_size = window_size
#         self.alpha = latency_weight # Penalty for latency
        
#         # 1. Action Space: 3 Discrete choices (YOLOv8 n, s, l)
#         self.action_space = spaces.Discrete(3)
        
#         # 2. Observation Space: 
#         # [32x32 grayscale pixels (flattened)] + [prev_model_idx, avg_conf, obj_count_delta]
#         # Total size = 1024 + 3 = 1027
#         self.observation_shape = 1027
#         self.observation_space = spaces.Box(
#             low=0, high=1, shape=(self.observation_shape,), dtype=np.float32
#         )

#         # Placeholder for loading your COCO metadata/ground truth
#         self.data = self._load_dataset(dataset_path)
#         self.current_step = 0

#     def reset(self, seed=None, options=None):
#         super().reset(seed=seed)
#         self.current_step = 0
        
#         # Return initial state (dummy for now, will come from features.py)
#         initial_obs = np.zeros(self.observation_shape, dtype=np.float32)
#         info = {}
#         return initial_obs, info

#     # def step(self, action):
#     #     """
#     #     Action: 0=Nano, 1=Small, 2=Large
#     #     """
#     #     # 1. Get "Ground Truth" for the current window of frames
#     #     # 2. Simulate/Get inference results for the selected model
#     #     accuracy, latency = self._get_model_performance(action)
        
#     #     # 3. Calculate Reward: R = Accuracy - (alpha * Latency)
#     #     # Note: You can add a 'switching penalty' here later
#     #     reward = accuracy - (self.alpha * latency)
        
#     #     # 4. Advance window
#     #     self.current_step += self.window_size
#     #     done = self.current_step >= len(self.data)
        
#     #     # 5. Get next observation
#     #     obs = self._get_next_obs()
        
#     #     return obs, reward, done, False, {}

#     # def _get_model_performance(self, action):
#     #     # This will eventually pull from a pre-computed benchmark file 
#     #     # or run live inference on your RTX 5060.
#     #     # Example dummy values:
#     #     perf_map = {
#     #         0: {"acc": 0.70, "lat": 0.008}, # Nano
#     #         1: {"acc": 0.85, "lat": 0.020}, # Small
#     #         2: {"acc": 0.95, "lat": 0.045}  # Large
#     #     }
#     #     return perf_map[action]["acc"], perf_map[action]["lat"]

#     def step(self, action):
#         # 1. Get the current window of image paths
#         window_paths = self.data[self.current_step : self.current_step + self.window_size]
        
#         # 2. Extract REAL features for the NEXT state
#         # We use the first frame of the next window as the 'representative' state
#         obs = self._get_next_obs() 

#         # 3. Dynamic Reward Logic (Simulated for Training)
#         # In a real MLOps pipeline, you'd use a lookup table of pre-run YOLO results
#         # For now, we scale dummy values by the "Edge Density" of the frame
#         edge_density = obs[1024] # Our 1025th feature is Edge Density
        
#         # If edge density is high (>0.5), Nano's accuracy drops significantly
#         base_acc = {0: 0.70, 1: 0.85, 2: 0.95}[action]
#         latency = {0: 0.008, 1: 0.020, 2: 0.045}[action]
        
#         # Penalty: Nano struggles with complex (high edge) scenes
#         if action == 0 and edge_density > 0.4:
#             accuracy = base_acc - (edge_density * 0.3) 
#         else:
#             accuracy = base_acc

#         reward = accuracy - (self.alpha * latency)
        
#         # 4. Advance
#         self.current_step += self.window_size
#         done = self.current_step + self.window_size >= len(self.data)
        
#         return obs, reward, done, False, {}

#     # def _get_next_obs(self):
#     #     # 1. Get the raw line from train.txt (e.g., "data/processed/images/train2017/000000000009.jpg")
#     #     img_rel_path = self.data[self.current_step].strip()
        
#     #     # 2. Identify the Project Root (where 'Data-Pipeline' lives)
#     #     script_dir = os.path.dirname(os.path.abspath(__file__))
#     #     project_root = os.path.abspath(os.path.join(script_dir, "../../../"))
        
#     #     # 3. Join them directly
#     #     full_path = os.path.join(project_root, img_rel_path)
        
#     #     # DEBUG: Run this once to see the clean path
#     #     # print(f"Trying to load: {full_path}") 

#     #     frame = cv2.imread(full_path)
#     #     if frame is None:
#     #         return np.zeros(self.observation_shape, dtype=np.float32)

#     #     # Use your FeatureExtractor to get the 1027-vector
#     #     from features import FeatureExtractor
#     #     fe = FeatureExtractor()
        
#     #     vis = fe.get_visual_features(frame)
#     #     edge = fe.get_edge_density(frame)
#     #     # Metadata: prev_model, dummy_conf, dummy_delta
#     #     metadata = [0.0, 0.8, 0.0] 
        
#     #     return fe.construct_state(vis, edge, metadata)


#     # def _get_next_obs(self):
#     #     # 1. Get the relative path from the split file (e.g., "data/processed/images/train2017/000000000009.jpg")
#     #     img_rel_path = self.data[self.current_step].strip()
        
#     #     # 2. Define the Project Root based on your find command
#     #     # This points to: /home/he-man/IE7374-MLOps-Adaptive-ML-Inference/
#     #     script_dir = os.path.dirname(os.path.abspath(__file__))
#     #     project_root = os.path.abspath(os.path.join(script_dir, "../../../"))
        
#     #     # 3. Join them to get the absolute path
#     #     # Result: /home/he-man/IE7374-MLOps-Adaptive-ML-Inference/Data-Pipeline/ + rel_path
#     #     full_path = os.path.join(project_root, "Data-Pipeline", img_rel_path)
        
#     #     frame = cv2.imread(full_path)
#     #     if frame is None:
#     #         # Debug print if an image fails to load
#     #         # print(f"DEBUG: Failed to load {full_path}")
#     #         return np.zeros(self.observation_shape, dtype=np.float32)

#     #     # 4. Extract features using your validated FeatureExtractor
#     #     from features import FeatureExtractor
#     #     fe = FeatureExtractor()
        
#     #     vis = fe.get_visual_features(frame) # Returns 1024 vector
#     #     edge = fe.get_edge_density(frame)   # Returns 1 vector
        
#     #     # Metadata: [prev_model_idx, avg_conf, obj_count_delta]
#     #     # (Using placeholders for conf and delta for training)
#     #     metadata = np.array([0.0, 0.8, 0.0], dtype=np.float32) 
        
#     #     return fe.construct_state(vis, edge, metadata) # Returns 1027 vector
#     # def _get_next_obs(self):
#     #     # This will interface with features.py later
#     #     return np.random.rand(self.observation_shape).astype(np.float32)


#     # def _load_dataset(self, path):
#     #     # Logic to point to your processed COCO images from DVC
#     #     # return []
#     #     # Path to the split file generated by your Data Pipeline
#     #     split_file = os.path.join(path, "../../splits/train.txt")
#     #     if os.path.exists(split_file):
#     #         with open(split_file, 'r') as f:
#     #             return f.readlines()
#     #     return []

#     def _get_next_obs(self):
#         if not self.data or self.current_step >= len(self.data):
#             return np.zeros(self.observation_shape, dtype=np.float32)

#         img_rel_path = self.data[self.current_step].strip()
        
#         # Use the absolute path we verified with 'find'
#         project_root = "/home/he-man/IE7374-MLOps-Adaptive-ML-Inference"
#         full_path = os.path.join(project_root, "Data-Pipeline", img_rel_path)

#         frame = cv2.imread(full_path)
#         if frame is None:
#             return np.zeros(self.observation_shape, dtype=np.float32)

#         # Feature Extraction
#         from features import FeatureExtractor
#         fe = FeatureExtractor()
#         vis = fe.get_visual_features(frame)
#         edge = fe.get_edge_density(frame)
#         metadata = np.array([0.0, 0.8, 0.0], dtype=np.float32) 
        
#         return fe.construct_state(vis, edge, metadata)

#     def _load_dataset(self, path):
#     # Get the absolute path to the directory where THIS script lives
#         script_dir = os.path.dirname(os.path.abspath(__file__))
        
#         # Traverse up to the project root and then to the splits folder
#         # RL is in src/RL -> ../../ gets us to model_pipeline root -> ../ gets us to project root
#         split_file = os.path.abspath(os.path.join(script_dir, "../../../Data-Pipeline/data/splits/train.txt"))
        
#         print(f"DEBUG: Looking for split file at: {split_file}") # Verification line
        
#         if os.path.exists(split_file):
#             with open(split_file, 'r') as f:
#                 lines = [line.strip() for line in f.readlines() if line.strip()]
#                 print(f"SUCCESS: Loaded {len(lines)} images from train.txt")
#                 return lines
                
#         print(f"ERROR: Could not find split file at {split_file}")
#         return []
    




import gymnasium as gym
from gymnasium import spaces
import numpy as np
import os
import cv2

class AdaptiveInferenceEnv(gym.Env):
    def __init__(self, dataset_path, window_size=10, latency_weight=0.5):
        super(AdaptiveInferenceEnv, self).__init__()
        self.window_size = window_size
        self.alpha = latency_weight 
        self.action_space = spaces.Discrete(3)
        
        # FIX: Changed from 1027 to 1028
        self.observation_shape = 1028 
        self.observation_space = spaces.Box(
            low=0, high=1, shape=(self.observation_shape,), dtype=np.float32
        )

        self.data = self._load_dataset(dataset_path)
        self.current_step = 0

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.current_step = 0
        return np.zeros(self.observation_shape, dtype=np.float32), {}

    def step(self, action):
        obs = self._get_next_obs() 
        edge_density = obs[1024] # 1025th element
        
        base_acc = {0: 0.70, 1: 0.85, 2: 0.95}[action]
        latency = {0: 0.008, 1: 0.020, 2: 0.045}[action]
        
        # Simulated penalty: Nano struggles with complex scenes
        if action == 0 and edge_density > 0.4:
            accuracy = base_acc - (edge_density * 0.3) 
        else:
            accuracy = base_acc

        reward = accuracy - (self.alpha * latency)
        self.current_step += self.window_size
        done = self.current_step + self.window_size >= len(self.data)
        
        return obs, reward, done, False, {}

    def _get_next_obs(self):
        if not self.data or self.current_step >= len(self.data):
            return np.zeros(self.observation_shape, dtype=np.float32)

        img_rel_path = self.data[self.current_step].strip()
        project_root = "/home/he-man/IE7374-MLOps-Adaptive-ML-Inference"
        full_path = os.path.join(project_root, "Data-Pipeline", img_rel_path)

        frame = cv2.imread(full_path)
        if frame is None:
            # If image fails, return 1028 zeros to prevent crash but log it
            if self.current_step == 0:
                print(f"CRITICAL ERROR: Could not load image at {full_path}")
            return np.zeros(self.observation_shape, dtype=np.float32)

        from features import FeatureExtractor
        fe = FeatureExtractor()
        vis = fe.get_visual_features(frame) # 1024
        edge = fe.get_edge_density(frame)   # 1
        metadata = np.array([0.0, 0.8, 0.0], dtype=np.float32) # 3
        
        return fe.construct_state(vis, edge, metadata) # Total 1028

    def _load_dataset(self, path):
        script_dir = os.path.dirname(os.path.abspath(__file__))
        split_file = os.path.abspath(os.path.join(script_dir, "../../../Data-Pipeline/data/splits/train.txt"))
        
        if os.path.exists(split_file):
            with open(split_file, 'r') as f:
                lines = [line.strip() for line in f.readlines() if line.strip()]
                print(f"SUCCESS: Loaded {len(lines)} images from train.txt")
                return lines
        return []


############# 

# Key Implementation Details
# Normalization: 
# Notice the observation space is low=0, high=1. 
# RL agents perform significantly better when inputs are normalized. 
# Your $32 \times 32$ pixel values should be divided by 255.

# The Step Function: 
# Instead of moving frame-by-frame, self.current_step increments by window_size. 
# This enforces your requirement that the RL agent only makes decisions for a set of frames.

# The Penalty Factor ($\alpha$): 
# This is where you control the "personality" of your agent.
# Set $\alpha$ high $\rightarrow$ The agent will prefer Nano to avoid the high penalty.
# Set $\alpha$ low $\rightarrow$ The agent will prefer Large because the accuracy gain is worth the small penalty.


# Dependencies to add to requirements.txt
# To run this, 
# you will need:
# gymnasium
# numpy
# torch (for the neural network in the agent later)